import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :civic_flux, CivicFluxWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: CivicFlux.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# EventStore config (Commanded)
config :civic_flux, CivicFlux.EventStore,
  serializer: Commanded.Serialization.JsonSerializer,
  username: "postgres",
  password: "postgres",
  database: "civic_flux_eventstore_prod",
  hostname: "localhost"

config :civic_flux, CivicFlux.Repo,
  username: "postgres",
  password: "postgres",
  database: "civic_flux_prod",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
